steps:
  # Build the container image with optimized caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'gcr.io/$PROJECT_ID/iris-ai:latest',
      '-t', 'gcr.io/$PROJECT_ID/iris-ai:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/iris-ai:latest',
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iris-ai:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iris-ai:latest']
  
  # Deploy container image to Cloud Run with Secret Manager integration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iris-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iris-ai:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1,HOSTNAME=0.0.0.0,PORT=3000'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,SESSION_SECRET=SESSION_SECRET:latest,NEXTAUTH_URL=NEXTAUTH_URL:latest,NEXT_PUBLIC_SITE_URL=NEXT_PUBLIC_SITE_URL:latest'
      - '--cpu-boost'
      - '--execution-environment'
      - 'gen2'
      - '--no-cpu-throttling'

images:
  - 'gcr.io/$PROJECT_ID/iris-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/iris-ai:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  env:
    - 'DOCKER_BUILDKIT=1'

