
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount environment variables file for local development
      - ./.env.local:/app/.env.local:ro
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://0.0.0.0:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
