apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iris-ai
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/cpu-boost: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/cpu-boost: "true"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/iris-ai:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_CLIENT_ID
                  key: latest
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_CLIENT_SECRET
                  key: latest
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: SESSION_SECRET
                  key: latest
            - name: PHOENIX_LOGIN_API_URL
              value: "http://portal.phoenixcalibrationdr.com/api/auth/login"
            - name: PHOENIX_LIST_API_URL
              value: "http://portal.phoenixcalibrationdr.com/api/Calibration/GetPendingToApproveCalibrationList"
            - name: PHOENIX_DETAIL_API_URL_TEMPLATE
              value: "http://portal.phoenixcalibrationdr.com/api/Calibration/GetCertificateDataByCertNo/{certNo}"
            - name: LIST_ALL_CERTIFICATES_API_URL
              value: "http://portal.phoenixcalibrationdr.com/api/Calibration/GetCertificatesDataListByEquipmentType"
            - name: SUPABASE_PORT
              value: "6543"
            - name: SUPABASE_DBNAME
              value: "postgress"
            - name: NEXT_PUBLIC_SITE_URL
              value: "https://iris-ai-PROJECT_ID.a.run.app"
            - name: NEXT_PUBLIC_SUPABASE_URL
              value: "https://zdxpdutejsnguwawlwbo.supabase.co"
            - name: SUPABASE_URL
              value: "https://zdxpdutejsnguwawlwbo.supabase.co"
            - name: NEXTAUTH_URL
              value: "https://iris-ai-PROJECT_ID.a.run.app"
            - name: PHOENIX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: USERNAME_PHOENIX_ENDPOINT
                  key: latest
            - name: PHOENIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: PASSWORD_PHOENIX_ENDPOINT
                  key: latest
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_SERVICE_ROLE_KEY
                  key: latest
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_KEY_WIZARD
                  key: latest
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
